name: 🔗 Check for Broken Links

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # runs weekly on Sunday at midnight

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Install lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'
